### PR TITLE
remove not working icons in footer

### LINKED ISSUE #9: Remove not working Icons
Twitter, Facebook and IG
image

### PR DESCRIPTION
**Pull request by nngrz**
Removed not working icons in footer, moved Github link to "Info" section. #9 
Screenshot 2024-09-16 at 17 34 07
Screenshot 2024-09-16 at 17 34 11

### CODE REVIEW

File: src/components/Footer.js [hunk 1]
```diff
@@ -2,13 +2,8 @@ import React from "react"
...
 export default function Footer() {
     return (
-        <nav className="icons">
-            <img src="images/twitter.png"></img>
-            <img src="images/facebook.png"></img>
-            <img src="images/ig.png"></img>
-            <a href="https://github.com/nngrz" target="_blank" rel="noopener noreferrer">
-                <img src="images/github.png" alt="GitHub Profile" className="icon-github" />
-            </a>
+        <nav className="footer--container">
```
Comment (balinskia) [inline src/components/Footer.js]: close the tag in the same line

**Review by balinskia — APPROVED** [review]
